name = "CanonicalForms"
defaultTargets = ["CanonicalForms"]

[[lean_lib]]
name = "CanonicalForms"

[[require]]
scope = "leanprover-community"
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.29.1"